version: '3.8'
services:
  database:
    image: mysql:latest
    container_name: mysql-api-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
